CREATE TABLE IF NOT EXISTS `PACIENTE` (
`ID` INTEGER (11) NOT NULL AUTO_INCREMENT,
`CPF` VARCHAR(11) NOT NULL,
`NOME` VARCHAR(100) NOT NULL,
`DATA_NASCIMENTO` DATE NOT NULL,
`ENDERECO` VARCHAR(60) NULL,
`Bairros_idBairros` INT(11) NOT NULL,
`CEP` VARCHAR(10) NOT NULL,
`NOME_MAE` VARCHAR(100) NULL,
`EMAIL` VARCHAR(100) NULL,
`NOME_SOCIAL`VARCHAR(100) NULL,
`PRONTUARIO`INT(7) NULL,
`UF_idUF` INT(11) NOT NULL, 
`Cidades_IdCidade` INT(11) NOT NULL, 
`Religiao_idReligiao` INT(11) NOT NULL,
`Tipo_Sanguineos_idTiposSanguineos` INT(11) NOT NULL,
`Plano_Saude_idPlano` INT(11) NOT NULL,
`Generos_idGeneros` INT(11) NOT NULL,
`Estado_Civil_idEstadosCivis` INT(11) NOT NULL,
`TELEFONE_IDTELEFONE` INT (20) NOT NULL,

PRIMARY KEY(ID),
 
CONSTRAINT `fk_Paciente_UF1`
	FOREIGN KEY (`UF_idUF`)
	REFERENCES `UF` (`IDUF`)
    ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	
	CONSTRAINT `fk_Paciente_Cidades1`
	FOREIGN KEY (`Cidades_IdCidade`)
	REFERENCES `CIDADES` (`IDCIDADE`)
    ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	
	CONSTRAINT `fk_Paciente_Religiao1`
	FOREIGN KEY (`Religiao_idReligiao`)
	REFERENCES `RELIGIAO` (`IDRELIGIAO`)
    ON DELETE NO ACTION
	ON UPDATE NO ACTION,

CONSTRAINT `fk_Paciente_Tipo_Sanguineos`
	FOREIGN KEY (`Tipo_Sanguineos_idTiposSanguineos`)
	REFERENCES `TIPO_SANGUINEOS` (`ID_TiposSanguineos`)
    ON DELETE NO ACTION
	ON UPDATE NO ACTION,

CONSTRAINT `fk_Paciente_Plano_Saude1`
	FOREIGN KEY (`Plano_Saude_idPlano`)
	REFERENCES `PLANO_SAUDE` (`IDPLANO`)
    ON DELETE NO ACTION
	ON UPDATE NO ACTION,

CONSTRAINT `fk_Paciente_Bairros1`
	FOREIGN KEY (`Bairros_idBairros`)
	REFERENCES `BAIRROS` (`IDBAIRROS`)
    ON DELETE NO ACTION
	ON UPDATE NO ACTION,

CONSTRAINT `fk_Paciente_Estado_Civil1`
	FOREIGN KEY (`Estado_Civil_idEstadosCivis`)
	REFERENCES `ESTADO_CIVIL` (`IDESTADOCIVIS`)
    ON DELETE NO ACTION
	ON UPDATE NO ACTION,

CONSTRAINT `fk_Paciente_Generos1`
	FOREIGN KEY (`Generos_idGeneros`)
	REFERENCES `GENEROS` (`IDGENEROS`)
    ON DELETE NO ACTION
	ON UPDATE NO ACTION,

CONSTRAINT `fk_Paciente_Telefone1`
	FOREIGN KEY (`TELEFONE_IDTELEFONE`)
	REFERENCES `TELEFONE` (`IDNUMERO`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);
	
	
	
	
	
	
	
	
	
	