CREATE TABLE GENEROS (
    IDGENEROS INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GENERO VARCHAR(45)
);

CREATE TABLE BAIRROS(
    IDBAIRROS INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BAIRROS VARCHAR(50)
);

CREATE TABLE TELEFONE(
    IDNUMERO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NR_TELEFONE VARCHAR(45)
);
CREATE TABLE ESTADO_CIVIL(
    IDESTADOCIVIS INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ESTADO_CIVIL VARCHAR(45)
);
CREATE TABLE PLANO_SAUDE(
    IDPLANO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PLANO VARCHAR(45),
    SITAUCAO VARCHAR(45)
);

 

CREATE TABLE RELIGIAO(
    IDRELIGIAO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);

 

CREATE TABLE CIDADES(
    IDCIDADE INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_CIDADE VARCHAR(255)
);

CREATE TABLE UF(
    IDUF INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SIGLA_UF VARCHAR(2)
);

 
CREATE TABLE TIPO_SANGUINEOS(
    ID_TiposSanguineos INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TiposSanguineo VARCHAR(11)
);